### ISSUE TITLE
Setting Up Stargazer Workflow

### ISSUE THREAD

**Issue by Sudhanshu-Ambastha** [BEPb/Vulnerabilities#1]
Hello, @BEPb, this is my first time setting up a workflow. I was trying to set up Stargazer in Chartist’s chart theme. I created a workflow for my main README. Currently, I’m testing it in a private README, and once it starts working, I’ll transfer it to public. However, I am unable to make it to the deployment. Below is the code, could you find out the error and resolve it?
```
name: Update Stargazers Chart

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Stargazers Chart
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}  # Replace with your actual secret name
          user: Sudhanshu-Ambastha
          template: classic
          base: repositories
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist
          committer_message: "chore: update stargazers chart"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update stargazers chart"
          git push
```
